config/routes.rb
Rails.application.routes.draw do
  # Tasks and subtasks
  resources :tasks do
    resources :subtasks
  end

  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Root home
  root to: 'tasks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/subtask.rb
class Subtask < ApplicationRecord
  belongs_to :task, inverse_of: :subtasks

  # Validation
  validates :name, presence: true, length: { minimum: 1 }
end

app/models/task.rb
class Task < ApplicationRecord
  has_many :subtasks, inverse_of: :task, :dependent => :delete_all
  accepts_nested_attributes_for :subtasks, :allow_destroy => true

  # Validation
  validates :name, presence: true, length: { minimum: 1 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/subtasks_controller.rb
class SubtasksController < ApplicationController
  # Authenticate (user login) prior to any actions
  before_action :authenticate_user!


  def index
    @all_subtasks = Subtask.all
  end

  def show
    @task = Task.find(params[:task_id])
    @subtask = Subtask.find(params[:id])

    redirect_to task_path(@task)
  end

  def new
    @task = Task.find(params[:task_id])
    @subtask = Subtask.new
  end

  def edit
      @task = Task.find(params[:task_id])
      @subtask = Subtask.find(params[:id])
  end

  def create
    @task = Task.find(params[:task_id])
    @subtask = @task.subtasks.create(allowed_params)

    respond_to do |format|
      format.html { redirect_to task_path(@task) }
      format.js
    end
  end

  def update
    @task = Task.find(params[:task_id])
    @subtask = Subtask.find(params[:id])

    respond_to do |format|
      if @subtask.update(allowed_params)
        format.html { redirect_to task_path(@task) }
        format.js
      else
        render :edit
      end
    end
  end

  def destroy
    @task = Task.find(params[:task_id])
    @subtask = Subtask.destroy(params[:id])

    respond_to do |format|
      format.html { redirect_to task_path(@task) }
      format.js
    end
  end


  private

    def allowed_params
      params.require(:subtask).permit(:name)
    end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  # Authenticate (user login) prior to any actions
  before_action :authenticate_user!


  def index
    # Display ALL public tasks and any private tasks for the signed-in user
    @task_list = Task.where("public_viewable = ? OR owner = ?", true, current_user.email)
  end

  def show
    begin
      @task = Task.find(params[:id])
    rescue Exception => e
      logger.error("ERROR: TasksController:show: #{e.message}")
      # TODO: Can probably add better handling...
      redirect_to root_url, alert: 'This task is no longer in the system; likely removed by the owner'
    end
  end

  def new
    @task = Task.new

    # This basically creates an empty subtasks shell, needed for seeding and forms
    @task.subtasks.build
  end

  def edit
    @task = Task.find(params[:id])
  end

  def create
    @task = Task.new(allowed_params)

    respond_to do |format|
      if @task.save
        format.html { redirect_to root_url, notice: 'Successfully created task.' }
        format.json { render :index, status: :created, location: @task }
      else
        format.html { render :new }
        format.json { render json: @task.errors, status: :unprocessable_entity}
      end
    end
  end

  def update
    @task = Task.find(params[:id])

    if @task.update(allowed_params)
      redirect_to root_url, notice: 'Successfully updated task.'
    else
      render :edit
    end
  end

  def destroy
    @task = Task.destroy(params[:id])

    redirect_to root_url, notice: 'Successfully deleted this task and any subtasks.'
  end


  private

    def allowed_params
      params.require(:task).permit(:owner, :public_viewable, :name, subtasks_attributes: [:id, :name, :_destroy])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/subtask_helper.rb
module SubtaskHelper
end

app/helpers/task_helper.rb
module TaskHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoList</title>

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  </head>

  <body>
    <%= yield %>
    <br>
    <br>
    <div id="notice_alert_div" class="bold_green_text">
      <p class="notice"><%= notice %></p>
    </div>
    <div id="notice_alert_div" class="bold_red_text">
      <p class="alert"><%= alert %></p>
    </div>
  </body>
</html>

app/views/subtasks/_form.html.erb
<%= simple_form_for @subtask, :url => @subtask.new_record? ? url_for(action: 'create') : url_for(action: 'update'), remote: true, :authenticity_token => true do |f| %>
  <p><%= f.input :name, autofocus: true %></p>
  <div id="default_button_div" >
    <p><%= f.button :submit %></p>
  </div>
<% end %>

app/views/subtasks/_subtask.html.erb
<%= div_for subtask, :url => subtask.new_record? ? url_for(action: 'create') : url_for(action: 'update'), :authenticity_token => true do %>
  <p>
    <strong>Name:</strong>
    <%= subtask.name %>
    <% if @task.owner == current_user.email %>
      <%= link_to 'Edit', edit_task_subtask_path(@task, subtask.id), remote: true %>
      <%= link_to 'Delete', task_subtask_path(@task, subtask.id), method: :delete, remote: true, data: { confirm: 'Are you sure you want to permanently delete this subtask?' } %>
    <% end %>
  </p>
<% end %>

app/views/subtasks/create.js.erb
$('form').hide();
// Append the new subtask to the list
$('.task_subtasks').append('<%= j render partial: 'subtask', locals: { subtask: @subtask } %>');
// Show the New Subtask button once again
$('.new_subtask_button').show();

app/views/subtasks/destroy.js.erb
// Remove the deleted subtask from the list
$('div#<%= dom_id(@subtask) %>').remove();

app/views/subtasks/edit.js.erb
$('form').hide();
$('div#<%= dom_id(@subtask) %>').replaceWith('<%= j render 'form' %>');

app/views/subtasks/new.js.erb
// Hide the New Subtask button after the user clicks on it and load the create form inline
$('.new_subtask_button').hide().after('<%= j render 'form' %>');

app/views/subtasks/update.js.erb
$('form').hide();
// Replace the updated subtask in the list -> id: edit_subtask_12
$('form#<%= dom_id(@subtask, :edit) %>').replaceWith('<%= j render partial: 'subtask', locals: { subtask: @subtask } %>');
$('form').show();

app/views/tasks/_form.html.erb
<%= simple_form_for @task, :url => @task.new_record? ? url_for(action: 'create') : url_for(action: 'update') do |f| %>
  <% if @task.errors.any? %>
    <div id="error_message">
      <h2>
        <%= pluralize(@task.errors.count, 'error') %> Not able to save task:
      </h2>
      <ul>
        <% @task.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p><%= f.input :owner, :as => :hidden, :input_html => { :value => current_user.email } %></p>
  <p><%= f.input :public_viewable, :as => :boolean, label: 'Public visibility', inline_label: true %></p>
  <p><%= f.input :name, label: 'Task Name:' %></p>
  <p><%= f.button :submit %></p>
<% end %>

app/views/tasks/edit.html.erb
<h1>Edit Task</h1>
<br>
<br>
<%= render 'form' %>
<br>
<br>
<p><%= link_to 'Back to Todo List', tasks_path %></p>

app/views/tasks/index.html.erb
<div id="logout_link_div">
  <p><%= link_to "Log Out", destroy_user_session_path, method: :delete %></p>
</div>

<div id="todo_list_div" class="form_bg_gray_grad default_border">
  <h1>TODO List</h1>

  <br>
  <br>
  <br>
  <br>

  <table id='todo_list_table' class="data_table">
    <tr>
      <th class="data_table">Owner</th>
      <th class="data_table">Task</th>
      <th class="data_table">Actions</th>
    </tr>

    <% if @task_list.blank? %>
      <tr>
        <td class="data_table"><p><i><strong>No tasks are currently in the system, please add below</strong></i></p></td>
        <td class="data_table"> </td>
        <td class="data_table"> </td>
      </tr>
    <% else %>
      <% @task_list.each do |task| %>
        <tr>
          <td class="data_table"><%= task.owner %></td>
          <td class="data_table"><%= task.name %></td>
          <td class="data_table">
            <%= link_to 'Show Details', task_path(task) %>
            <% if task.owner == current_user.email %>
              <%= link_to 'Edit', edit_task_path(task) %>
              <%= link_to 'Delete', task_path(task), method: :delete, data: { confirm: 'Are you sure you want to permanently delete this task?' } %>
            <% end %>
          </td>
        </tr>
      <% end %>
    <% end %>
  </table>

  <br>
  <br>

  <div id="new_task_link_div" class="default_link_div">
    <p><%= link_to 'New Task', new_task_path, id: 'new_link' %></p>
  </div>
</div>

app/views/tasks/new.html.erb
<h1>New Task</h1>

<%= render 'form' %>

<p><%= link_to "Back to tasks", tasks_path %></p>

app/views/tasks/show.html.erb
<div id="task_details_div" class="default_centered_div">

  <h1>Task details</h1>

  <div id="task_details_form_div">
    <% if @task.blank? %>
      <p><i><strong>No tasks are currently in the system</strong></i></p>
    <% else %>
      <p>
        <strong>Owner:</strong>
        <%= @task.owner %>
      </p>
      <p>
        <strong>Public:</strong>
        <%= @task.public_viewable %>
      </p>
      <p>
        <strong>Name:</strong>
        <%= @task.name %>
      </p>
      <% if @task.owner == current_user.email %>
        <div id="edit_task_link_div" class="default_link_div">
          <p><%= link_to 'Edit Task', edit_task_path(@task) %></p>
        </div>
      <% end %>

      <div id="task_subtask_details_div">
        <h2>SubTasks</h2>

        <% if @task.subtasks.blank? %>
          <p><i><strong>None</strong></i></p>
        <% else %>
          <% @task.subtasks.each do |subtask| %>
            <%= render subtask %>
          <% end %>
        <% end %>
        <% if @task.owner == current_user.email %>
          <div id="new_subtask_button_div">
            <%= button_to 'New Subtask', new_task_subtask_path(@task), method: :get, class: 'new_subtask_button', remote: true %>
          </div>
        <% end %>

        <div id="back_link_div" class="default_link_div">
          <p><%= link_to 'Back to Todo List', tasks_path %></p>
        </div>
      <% end %>
    </div>
  </div>
</div>